PlatziLabs/playground-challenges

- src/challenges/js/jsbasico-01/README.md
> Fix Retorna el Tipo, Curso Básico de JavaScript

- src/challenges/js/jsbasico-01/README.md
> Fix Solution to Retorna el Tipo, Curso Básico de JavaScript

- src/challenges/js/jsbasico-03/README.md
Claridad sobre agregar o no el punto final para pasar las pruebas.
> Fix Tienda de Tecnología, Curso Básico de JavaScript

- src/challenges/js/jsbasico-03/README.md
Claridad sobre agregar o no el punto final para pasar las pruebas.
> Fix Solution to Tienda de Tecnología, Curso Básico de JavaScript

- src/challenges/js/math-operations/src/exercise.js
Reverts PlatziLabs/playground-challenges#87 🤦
> Revert "Add solution: math-operations for Desafíos de pensamiento lógico"

- src/challenges/py/proalgoritmoslineales-05/.gitignore
- src/challenges/py/proalgoritmoslineales-05/README.md
- src/challenges/py/proalgoritmoslineales-05/playground.json
- src/challenges/py/proalgoritmoslineales-05/requirements.txt
- src/challenges/py/proalgoritmoslineales-05/src/main.py
- src/challenges/py/proalgoritmoslineales-05/src/main_test.py
- src/challenges/py/proalgoritmoslineales-05/src/tests.py
Este ejercicio debe agregarse a la plataforma DESPUÉS de ver la solución de la profesora, no antes como los demás.
> New Challenge: Parenthesis, Algoritmos Avanzados: Lineales 5 (post class) 🙏

- src/challenges/js/30DaysJs-10/README.md
> fix solution: challenge 30 dias de js 10, task planner

- src/challenges/js/30DaysJs-10/README.md
> fix challenge: challenge 30 dias de js 10, task planner

- src/challenges/js/30DaysJs-06/src/exercise.test.js
> Fix challenge: challenge 30 dias de js 06, Calcula el promedio

- src/challenges/js/30DaysJs-06/src/exercise.test.js
> Fix solution: challenge 30 dias de js 06, Calcula el promedio

- src/challenges/js/30DaysJs-10/README.md
> fix challenge: task planner, challenge 30 dias de js

- src/challenges/js/30DaysJs-10/README.md
> fix solution: task planner, challenge 30 dias de js

- src/challenges/js/30DaysJs-18/README.md
> fix challenge: hotel system, challenge 30 dias de js

- src/challenges/js/30DaysJs-01/README.md
> fix challenge: calculateTip, challenge 30 dias de js

- src/challenges/js/30DaysJs-01/README.md
> fix solution: calculateTip, challenge 30 dias de js

- src/challenges/js/30DaysJs-02/README.md
- src/challenges/js/30DaysJs-02/src/exercise.test.js
> Fix solution: isLeapYear, challenge 30 dias de js

- src/challenges/js/30DaysJs-23/README.md
> fix challenge: Encapsula datos de usuarios, challenge 30 dias de js

- src/challenges/js/30DaysJs-09/src/exercise.test.js
> fix challenge: Crea tu propio metodo map, challenge 30 dias de js

- src/challenges/js/30DaysJs-23/README.md
> fix solution: Encapsula datos de usuarios, challenge 30 dias de js

- src/challenges/js/30DaysJs-09/src/exercise.test.js
> fix solution: crea tu propio método map, challenge 30 dias de js

- src/challenges/js/30DaysJs-20/src/exercise.test.js
> fix challenge: Modifica el prototype de los arrays, challenge 30 dias de javascript 

- src/challenges/js/30DaysJs-20/src/exercise.test.js
> fix solution: Modifica el prototype de los arrays, challenge 30 dias de javascript

- src/challenges/js/30DaysJs-19/README.md
- src/challenges/js/30DaysJs-22/README.md
- src/challenges/js/30DaysJs-22/src/exercise.test.js
> fix challenge: 19 & 22, challenge 30 dias de js

- src/challenges/js/30DaysJs-19/README.md
- src/challenges/js/30DaysJs-19/playground.json
- src/challenges/js/30DaysJs-22/README.md
- src/challenges/js/30DaysJs-22/src/exercise.js
- src/challenges/js/30DaysJs-22/src/exercise.test.js
> fix soution: excercise 19 & 22, challenge 30 dias de JS

- src/challenges/sql/dbfundamentos-create/.gitignore
- src/challenges/sql/dbfundamentos-create/README.md
- src/challenges/sql/dbfundamentos-create/playground.json
- src/challenges/sql/dbfundamentos-create/requirements.txt
- src/challenges/sql/dbfundamentos-create/src/exercise.sql
- src/challenges/sql/dbfundamentos-create/src/main_test.py
- src/challenges/sql/dbfundamentos-create/src/tests.py
- src/challenges/sql/dbfundamentos-create/src/utils.py
- src/challenges/sql/dbfundamentos-select/README.md
> New Challenge: CREATE TABLE, Fundamentos DBs

- src/challenges/sql/mariadb-select/.gitignore
- src/challenges/sql/mariadb-select/README.md
- src/challenges/sql/mariadb-select/playground.json
- src/challenges/sql/mariadb-select/requirements.txt
- src/challenges/sql/mariadb-select/src/exercise.sql
- src/challenges/sql/mariadb-select/src/main_test.py
- src/challenges/sql/mariadb-select/src/setup.sql
- src/challenges/sql/mariadb-select/src/tests.py
- src/challenges/sql/mariadb-select/src/utils.py
> New Challenge: SELECT, MariaDB

- src/challenges/sql/mariadb-iud/.gitignore
- src/challenges/sql/mariadb-iud/README.md
- src/challenges/sql/mariadb-iud/playground.json
- src/challenges/sql/mariadb-iud/requirements.txt
- src/challenges/sql/mariadb-iud/src/exercise.sql
- src/challenges/sql/mariadb-iud/src/main_test.py
- src/challenges/sql/mariadb-iud/src/setup.sql
- src/challenges/sql/mariadb-iud/src/tests.py
- src/challenges/sql/mariadb-iud/src/utils.py
> New Challenge: Insert, Update & Delete, MariaDB

- src/challenges/sql/mariadb-tables/.gitignore
- src/challenges/sql/mariadb-tables/README.md
- src/challenges/sql/mariadb-tables/playground.json
- src/challenges/sql/mariadb-tables/requirements.txt
- src/challenges/sql/mariadb-tables/src/exercise.sql
- src/challenges/sql/mariadb-tables/src/main_test.py
- src/challenges/sql/mariadb-tables/src/setup.sql
- src/challenges/sql/mariadb-tables/src/tests.py
- src/challenges/sql/mariadb-tables/src/utils.py
> New Challenge: CREATE & ALTER, MariaDB

- src/challenges/sql/dbfundamentos-platziblog/.gitignore
- src/challenges/sql/dbfundamentos-platziblog/README.md
- src/challenges/sql/dbfundamentos-platziblog/playground.json
- src/challenges/sql/dbfundamentos-platziblog/requirements.txt
- src/challenges/sql/dbfundamentos-platziblog/src/exercise.sql
- src/challenges/sql/dbfundamentos-platziblog/src/main_test.py
- src/challenges/sql/dbfundamentos-platziblog/src/setup.sql
- src/challenges/sql/dbfundamentos-platziblog/src/tests.py
- src/challenges/sql/dbfundamentos-platziblog/src/utils.py
> New Challenge: PlatziBlogComments, Fundamentos DBs

- src/challenges/sql/dbfundamentos-helloworld/.gitignore
- src/challenges/sql/dbfundamentos-helloworld/README.md
- src/challenges/sql/dbfundamentos-helloworld/playground.json
- src/challenges/sql/dbfundamentos-helloworld/requirements.txt
- src/challenges/sql/dbfundamentos-helloworld/src/exercise.sql
- src/challenges/sql/dbfundamentos-helloworld/src/main_test.py
- src/challenges/sql/dbfundamentos-helloworld/src/setup.sql
- src/challenges/sql/dbfundamentos-helloworld/src/tests.py
- src/challenges/sql/dbfundamentos-helloworld/src/utils.py
> New Challenge: helloworld, DB Fundamentos

- src/challenges/sql/dbfundamentos-create/README.md
> Fix readme instructions

- src/challenges/sql/dbfundamentos-dml/.gitignore
- src/challenges/sql/dbfundamentos-dml/README.md
- src/challenges/sql/dbfundamentos-dml/playground.json
- src/challenges/sql/dbfundamentos-dml/requirements.txt
- src/challenges/sql/dbfundamentos-dml/src/exercise.sql
- src/challenges/sql/dbfundamentos-dml/src/main_test.py
- src/challenges/sql/dbfundamentos-dml/src/setup.sql
- src/challenges/sql/dbfundamentos-dml/src/tests.py
- src/challenges/sql/dbfundamentos-dml/src/utils.py
> new challenge: dml, fundamentos db

- src/challenges/sql/dbfundamentos-create/README.md
> Improvement how to create table in readme

- src/challenges/js/controlar-acceso-getters-setters/README.md
- src/challenges/js/override-inheritance/README.md
> Fixing typos in READMEs for two excercises

- src/challenges/py/30DaysPy-00/.gitignore
- src/challenges/py/30DaysPy-00/README.md
- src/challenges/py/30DaysPy-00/playground.json
- src/challenges/py/30DaysPy-00/requirements.txt
- src/challenges/py/30DaysPy-00/src/main.py
- src/challenges/py/30DaysPy-00/src/main_test.py
- src/challenges/py/30DaysPy-00/src/tests.py
> New challenge: retorna el tipo, challenge 30 dias de py

- src/challenges/py/30DaysPy-00/.gitignore
- src/challenges/py/30DaysPy-00/README.md
- src/challenges/py/30DaysPy-00/playground.json
- src/challenges/py/30DaysPy-00/requirements.txt
- src/challenges/py/30DaysPy-00/src/main.py
- src/challenges/py/30DaysPy-00/src/main_test.py
- src/challenges/py/30DaysPy-00/src/tests.py
> solution to Retorna el tipo, challenge 30 dias de python

- src/challenges/py/30DaysPy-01/.gitignore
- src/challenges/py/30DaysPy-01/README.md
- src/challenges/py/30DaysPy-01/playground.json
- src/challenges/py/30DaysPy-01/requirements.txt
- src/challenges/py/30DaysPy-01/src/main.py
- src/challenges/py/30DaysPy-01/src/main_test.py
- src/challenges/py/30DaysPy-01/src/tests.py
> solution to calculate_tip, challenge 30 dias de py

- src/challenges/py/30DaysPy-01/.gitignore
- src/challenges/py/30DaysPy-01/README.md
- src/challenges/py/30DaysPy-01/playground.json
- src/challenges/py/30DaysPy-01/requirements.txt
- src/challenges/py/30DaysPy-01/src/main.py
- src/challenges/py/30DaysPy-01/src/main_test.py
- src/challenges/py/30DaysPy-01/src/tests.py
> New challenge: calculate_tip, challenge 30 dias de py

- src/challenges/py/30DaysPy-02/.gitignore
- src/challenges/py/30DaysPy-02/README.md
- src/challenges/py/30DaysPy-02/playground.json
- src/challenges/py/30DaysPy-02/requirements.txt
- src/challenges/py/30DaysPy-02/src/main.py
- src/challenges/py/30DaysPy-02/src/main_test.py
- src/challenges/py/30DaysPy-02/src/tests.py
> new challenge: is_leap_year, challenge 30 dias de py

- src/challenges/py/30DaysPy-03/.gitignore
- src/challenges/py/30DaysPy-03/README.md
- src/challenges/py/30DaysPy-03/playground.json
- src/challenges/py/30DaysPy-03/requirements.txt
- src/challenges/py/30DaysPy-03/src/main.py
- src/challenges/py/30DaysPy-03/src/main_test.py
- src/challenges/py/30DaysPy-03/src/tests.py
> new challenge: print_triangle, challenge 30 dias de py

- src/challenges/py/30DaysPy-04/.gitignore
- src/challenges/py/30DaysPy-04/README.md
- src/challenges/py/30DaysPy-04/playground.json
- src/challenges/py/30DaysPy-04/requirements.txt
- src/challenges/py/30DaysPy-04/src/main.py
- src/challenges/py/30DaysPy-04/src/main_test.py
- src/challenges/py/30DaysPy-04/src/tests.py
> solution to find_famous_cat, challenge 30 dias de py

- src/challenges/py/30DaysPy-04/.gitignore
- src/challenges/py/30DaysPy-04/README.md
- src/challenges/py/30DaysPy-04/playground.json
- src/challenges/py/30DaysPy-04/requirements.txt
- src/challenges/py/30DaysPy-04/src/main.py
- src/challenges/py/30DaysPy-04/src/main_test.py
- src/challenges/py/30DaysPy-04/src/tests.py
> new challenge: find_famous_cat, challenge 30 dias de py

- src/challenges/py/30DaysPy-05/.gitignore
- src/challenges/py/30DaysPy-05/README.md
- src/challenges/py/30DaysPy-05/playground.json
- src/challenges/py/30DaysPy-05/requirements.txt
- src/challenges/py/30DaysPy-05/src/main.py
- src/challenges/py/30DaysPy-05/src/main_test.py
- src/challenges/py/30DaysPy-05/src/tests.py
> solution to get_student_average, challenge 30 dias de py

- src/challenges/py/30DaysPy-05/.gitignore
- src/challenges/py/30DaysPy-05/README.md
- src/challenges/py/30DaysPy-05/playground.json
- src/challenges/py/30DaysPy-05/requirements.txt
- src/challenges/py/30DaysPy-05/src/main.py
- src/challenges/py/30DaysPy-05/src/main_test.py
- src/challenges/py/30DaysPy-05/src/tests.py
> new challenge: get_student_average, challenge 30 dias de py

- src/challenges/py/30DaysPy-06/.gitignore
- src/challenges/py/30DaysPy-06/README.md
- src/challenges/py/30DaysPy-06/playground.json
- src/challenges/py/30DaysPy-06/requirements.txt
- src/challenges/py/30DaysPy-06/src/main.py
- src/challenges/py/30DaysPy-06/src/main_test.py
- src/challenges/py/30DaysPy-06/src/tests.py
> Solution to get_packages_info, challenge 30 dias de py

- src/challenges/py/30DaysPy-06/.gitignore
- src/challenges/py/30DaysPy-06/README.md
- src/challenges/py/30DaysPy-06/playground.json
- src/challenges/py/30DaysPy-06/requirements.txt
- src/challenges/py/30DaysPy-06/src/main.py
- src/challenges/py/30DaysPy-06/src/main_test.py
- src/challenges/py/30DaysPy-06/src/tests.py
> new challenge: get_packages_info, challenge 30 dias de py

- src/challenges/py/30DaysPy-07/.gitignore
- src/challenges/py/30DaysPy-07/README.md
- src/challenges/py/30DaysPy-07/playground.json
- src/challenges/py/30DaysPy-07/requirements.txt
- src/challenges/py/30DaysPy-07/src/main.py
- src/challenges/py/30DaysPy-07/src/main_test.py
- src/challenges/py/30DaysPy-07/src/tests.py
> solution to count_letters, challenge 30 dias de py

- src/challenges/py/30DaysPy-07/.gitignore
- src/challenges/py/30DaysPy-07/README.md
- src/challenges/py/30DaysPy-07/playground.json
- src/challenges/py/30DaysPy-07/requirements.txt
- src/challenges/py/30DaysPy-07/src/main.py
- src/challenges/py/30DaysPy-07/src/main_test.py
- src/challenges/py/30DaysPy-07/src/tests.py
> new challenge: count_letters, challenge 30 dias de py

- src/challenges/py/30DaysPy-08/.gitignore
- src/challenges/py/30DaysPy-08/README.md
- src/challenges/py/30DaysPy-08/playground.json
- src/challenges/py/30DaysPy-08/requirements.txt
- src/challenges/py/30DaysPy-08/src/main.py
- src/challenges/py/30DaysPy-08/src/main_test.py
- src/challenges/py/30DaysPy-08/src/tests.py
> solution to find_largest_palindrome, challenge 30 dias de py

- src/challenges/py/30DaysPy-08/.gitignore
- src/challenges/py/30DaysPy-08/README.md
- src/challenges/py/30DaysPy-08/playground.json
- src/challenges/py/30DaysPy-08/requirements.txt
- src/challenges/py/30DaysPy-08/src/main.py
- src/challenges/py/30DaysPy-08/src/main_test.py
- src/challenges/py/30DaysPy-08/src/tests.py
> new challenge: find_largest_palindrome, challenge 30 dias de py

- src/challenges/py/30DaysPy-09/.gitignore
- src/challenges/py/30DaysPy-09/README.md
- src/challenges/py/30DaysPy-09/playground.json
- src/challenges/py/30DaysPy-09/requirements.txt
- src/challenges/py/30DaysPy-09/src/main.py
- src/challenges/py/30DaysPy-09/src/main_test.py
- src/challenges/py/30DaysPy-09/src/tests.py
> solution to find_set_intersection, challenge 30 dias de py

- src/challenges/py/30DaysPy-09/.gitignore
- src/challenges/py/30DaysPy-09/README.md
- src/challenges/py/30DaysPy-09/playground.json
- src/challenges/py/30DaysPy-09/requirements.txt
- src/challenges/py/30DaysPy-09/src/main.py
- src/challenges/py/30DaysPy-09/src/main_test.py
- src/challenges/py/30DaysPy-09/src/tests.py
> new challenge: find_set_intersection, challenge 30 dias de py

- src/challenges/py/30DaysPy-10/.gitignore
- src/challenges/py/30DaysPy-10/README.md
- src/challenges/py/30DaysPy-10/playground.json
- src/challenges/py/30DaysPy-10/requirements.txt
- src/challenges/py/30DaysPy-10/src/main.py
- src/challenges/py/30DaysPy-10/src/main_test.py
- src/challenges/py/30DaysPy-10/src/tests.py
> solution to find_words_with_two_vowels, challenge 30 days py

- src/challenges/py/30DaysPy-10/.gitignore
- src/challenges/py/30DaysPy-10/README.md
- src/challenges/py/30DaysPy-10/playground.json
- src/challenges/py/30DaysPy-10/requirements.txt
- src/challenges/py/30DaysPy-10/src/main.py
- src/challenges/py/30DaysPy-10/src/main_test.py
- src/challenges/py/30DaysPy-10/src/tests.py
> new challenge: find_word_with_two_vowels, challenge 30 days py

- src/challenges/py/30DaysPy-11/.gitignore
- src/challenges/py/30DaysPy-11/README.md
- src/challenges/py/30DaysPy-11/playground.json
- src/challenges/py/30DaysPy-11/requirements.txt
- src/challenges/py/30DaysPy-11/src/main.py
- src/challenges/py/30DaysPy-11/src/main_test.py
- src/challenges/py/30DaysPy-11/src/tests.py
> solution to count_words_by_length, challenge 30 dias de py

- src/challenges/py/30DaysPy-11/.gitignore
- src/challenges/py/30DaysPy-11/README.md
- src/challenges/py/30DaysPy-11/playground.json
- src/challenges/py/30DaysPy-11/requirements.txt
- src/challenges/py/30DaysPy-11/src/main.py
- src/challenges/py/30DaysPy-11/src/main_test.py
- src/challenges/py/30DaysPy-11/src/tests.py
> new challenge: count_words_by_length, challenge 30 dias de py

- src/challenges/py/30DaysPy-12/.gitignore
- src/challenges/py/30DaysPy-12/README.md
- src/challenges/py/30DaysPy-12/playground.json
- src/challenges/py/30DaysPy-12/requirements.txt
- src/challenges/py/30DaysPy-12/src/main.py
- src/challenges/py/30DaysPy-12/src/main_test.py
- src/challenges/py/30DaysPy-12/src/tests.py
> solution to filter_user_messages, challenge 30 dias de py

- src/challenges/py/30DaysPy-12/.gitignore
- src/challenges/py/30DaysPy-12/README.md
- src/challenges/py/30DaysPy-12/playground.json
- src/challenges/py/30DaysPy-12/requirements.txt
- src/challenges/py/30DaysPy-12/src/main.py
- src/challenges/py/30DaysPy-12/src/main_test.py
- src/challenges/py/30DaysPy-12/src/tests.py
> new challenge: filter_user_messages, challenge 30 dias de py

- src/challenges/py/30DaysOfPy-13/.gitignore
- src/challenges/py/30DaysOfPy-13/README.md
- src/challenges/py/30DaysOfPy-13/playground.json
- src/challenges/py/30DaysOfPy-13/requirements.txt
- src/challenges/py/30DaysOfPy-13/src/main.py
- src/challenges/py/30DaysOfPy-13/src/main_test.py
- src/challenges/py/30DaysOfPy-13/src/tests.py
> solution to my_map, challenge 30 dias de py

- src/challenges/py/30DaysOfPy-13/.gitignore
- src/challenges/py/30DaysOfPy-13/README.md
- src/challenges/py/30DaysOfPy-13/playground.json
- src/challenges/py/30DaysOfPy-13/requirements.txt
- src/challenges/py/30DaysOfPy-13/src/main.py
- src/challenges/py/30DaysOfPy-13/src/main_test.py
- src/challenges/py/30DaysOfPy-13/src/tests.py
> new challenge: my_map, challenge 30 dias de py

- src/challenges/py/30DaysPy-14/.gitignore
- src/challenges/py/30DaysPy-14/README.md
- src/challenges/py/30DaysPy-14/playground.json
- src/challenges/py/30DaysPy-14/requirements.txt
- src/challenges/py/30DaysPy-14/src/main.py
- src/challenges/py/30DaysPy-14/src/main_test.py
- src/challenges/py/30DaysPy-14/src/tests.py
> solution to calculate_average, challenge 30 dias de py

- src/challenges/py/30DaysPy-14/.gitignore
- src/challenges/py/30DaysPy-14/README.md
- src/challenges/py/30DaysPy-14/playground.json
- src/challenges/py/30DaysPy-14/requirements.txt
- src/challenges/py/30DaysPy-14/src/main.py
- src/challenges/py/30DaysPy-14/src/main_test.py
- src/challenges/py/30DaysPy-14/src/tests.py
> new challenge: calculate_average, challenge 30 dias de py

- src/challenges/py/30DaysPy-15/.gitignore
- src/challenges/py/30DaysPy-15/README.md
- src/challenges/py/30DaysPy-15/playground.json
- src/challenges/py/30DaysPy-15/requirements.txt
- src/challenges/py/30DaysPy-15/src/main.py
- src/challenges/py/30DaysPy-15/src/main_test.py
- src/challenges/py/30DaysPy-15/src/tests.py
> solution to calculate_discount_price, challenge 30 dias de py

- src/challenges/py/30DaysPy-15/.gitignore
- src/challenges/py/30DaysPy-15/README.md
- src/challenges/py/30DaysPy-15/playground.json
- src/challenges/py/30DaysPy-15/requirements.txt
- src/challenges/py/30DaysPy-15/src/main.py
- src/challenges/py/30DaysPy-15/src/main_test.py
- src/challenges/py/30DaysPy-15/src/tests.py
> new challenge calculate_discount_price, challenge 30 dias de py

- src/challenges/py/30DaysPy-18/.gitignore
- src/challenges/py/30DaysPy-18/README.md
- src/challenges/py/30DaysPy-18/playground.json
- src/challenges/py/30DaysPy-18/requirements.txt
- src/challenges/py/30DaysPy-18/src/main.py
- src/challenges/py/30DaysPy-18/src/main_test.py
- src/challenges/py/30DaysPy-18/src/tests.py
> solution to car class, challenge 30 dias de py

- src/challenges/py/30DaysPy-18/.gitignore
- src/challenges/py/30DaysPy-18/README.md
- src/challenges/py/30DaysPy-18/playground.json
- src/challenges/py/30DaysPy-18/requirements.txt
- src/challenges/py/30DaysPy-18/src/main.py
- src/challenges/py/30DaysPy-18/src/main_test.py
- src/challenges/py/30DaysPy-18/src/tests.py
>  new challenge car class, challenge 30 dias de py 

- src/challenges/py/30DaysPy-19/.gitignore
- src/challenges/py/30DaysPy-19/README.md
- src/challenges/py/30DaysPy-19/playground.json
- src/challenges/py/30DaysPy-19/requirements.txt
- src/challenges/py/30DaysPy-19/src/main.py
- src/challenges/py/30DaysPy-19/src/main_test.py
- src/challenges/py/30DaysPy-19/src/product.py
- src/challenges/py/30DaysPy-19/src/tests.py
> solution to cart system, challenge 30 dias de py

- src/challenges/py/30DaysPy-19/.gitignore
- src/challenges/py/30DaysPy-19/README.md
- src/challenges/py/30DaysPy-19/playground.json
- src/challenges/py/30DaysPy-19/requirements.txt
- src/challenges/py/30DaysPy-19/src/main.py
- src/challenges/py/30DaysPy-19/src/main_test.py
- src/challenges/py/30DaysPy-19/src/product.py
- src/challenges/py/30DaysPy-19/src/tests.py
> new challenge cart system, challenge 30 dias de py

- src/challenges/py/30DaysPy-20/.gitignore
- src/challenges/py/30DaysPy-20/README.md
- src/challenges/py/30DaysPy-20/playground.json
- src/challenges/py/30DaysPy-20/requirements.txt
- src/challenges/py/30DaysPy-20/src/main.py
- src/challenges/py/30DaysPy-20/src/main_test.py
- src/challenges/py/30DaysPy-20/src/tests.py
> solution to protect users, challenge 30 dias de py

- src/challenges/py/30DaysPy-20/.gitignore
- src/challenges/py/30DaysPy-20/README.md
- src/challenges/py/30DaysPy-20/playground.json
- src/challenges/py/30DaysPy-20/requirements.txt
- src/challenges/py/30DaysPy-20/src/main.py
- src/challenges/py/30DaysPy-20/src/main_test.py
- src/challenges/py/30DaysPy-20/src/tests.py
> new challenge protect users, challenge 30 dias de py

- src/challenges/py/30DaysPy-21/.gitignore
- src/challenges/py/30DaysPy-21/README.md
- src/challenges/py/30DaysPy-21/playground.json
- src/challenges/py/30DaysPy-21/requirements.txt
- src/challenges/py/30DaysPy-21/src/main.py
- src/challenges/py/30DaysPy-21/src/main_test.py
- src/challenges/py/30DaysPy-21/src/tests.py
> Solution to animal hierarchy, challenge 30 dias de py

- src/challenges/py/30DaysPy-21/.gitignore
- src/challenges/py/30DaysPy-21/README.md
- src/challenges/py/30DaysPy-21/playground.json
- src/challenges/py/30DaysPy-21/requirements.txt
- src/challenges/py/30DaysPy-21/src/main.py
- src/challenges/py/30DaysPy-21/src/main_test.py
- src/challenges/py/30DaysPy-21/src/tests.py
> new challenge animal hierarchy, challenge 30 dias de py

- src/challenges/py/30DaysPy-22/.gitignore
- src/challenges/py/30DaysPy-22/README.md
- src/challenges/py/30DaysPy-22/playground.json
- src/challenges/py/30DaysPy-22/requirements.txt
- src/challenges/py/30DaysPy-22/src/card.py
- src/challenges/py/30DaysPy-22/src/cash.py
- src/challenges/py/30DaysPy-22/src/main.py
- src/challenges/py/30DaysPy-22/src/main_test.py
- src/challenges/py/30DaysPy-22/src/pay.py
- src/challenges/py/30DaysPy-22/src/paypal.py
- src/challenges/py/30DaysPy-22/src/tests.py
> solution to pay system, challenge 30 dias de py

- src/challenges/py/30DaysPy-22/.gitignore
- src/challenges/py/30DaysPy-22/README.md
- src/challenges/py/30DaysPy-22/playground.json
- src/challenges/py/30DaysPy-22/requirements.txt
- src/challenges/py/30DaysPy-22/src/card.py
- src/challenges/py/30DaysPy-22/src/cash.py
- src/challenges/py/30DaysPy-22/src/main.py
- src/challenges/py/30DaysPy-22/src/main_test.py
- src/challenges/py/30DaysPy-22/src/pay.py
- src/challenges/py/30DaysPy-22/src/paypal.py
- src/challenges/py/30DaysPy-22/src/tests.py
> new challenge pay system, challenge 30 dias de py

- src/challenges/py/30DaysPy-24/.gitignore
- src/challenges/py/30DaysPy-24/README.md
- src/challenges/py/30DaysPy-24/playground.json
- src/challenges/py/30DaysPy-24/requirements.txt
- src/challenges/py/30DaysPy-24/src/main.py
- src/challenges/py/30DaysPy-24/src/main_test.py
- src/challenges/py/30DaysPy-24/src/tests.py
> new challenge own list, challenge 30 dias de py

- src/challenges/py/30DaysPy-24/.gitignore
- src/challenges/py/30DaysPy-24/README.md
- src/challenges/py/30DaysPy-24/playground.json
- src/challenges/py/30DaysPy-24/requirements.txt
- src/challenges/py/30DaysPy-24/src/main.py
- src/challenges/py/30DaysPy-24/src/main_test.py
- src/challenges/py/30DaysPy-24/src/tests.py
> solution to own arr, challenge 30 dias de py

- src/challenges/py/30DaysPy-25/.gitignore
- src/challenges/py/30DaysPy-25/README.md
- src/challenges/py/30DaysPy-25/playground.json
- src/challenges/py/30DaysPy-25/requirements.txt
- src/challenges/py/30DaysPy-25/src/main.py
- src/challenges/py/30DaysPy-25/src/main_test.py
- src/challenges/py/30DaysPy-25/src/tests.py
> solution to contactList, challenge 30 dias de py

- src/challenges/py/30DaysPy-25/.gitignore
- src/challenges/py/30DaysPy-25/README.md
- src/challenges/py/30DaysPy-25/playground.json
- src/challenges/py/30DaysPy-25/requirements.txt
- src/challenges/py/30DaysPy-25/src/main.py
- src/challenges/py/30DaysPy-25/src/main_test.py
- src/challenges/py/30DaysPy-25/src/tests.py
> new challenge hash table, challenge 30 dias de py

- src/challenges/py/30DaysPy-26/.gitignore
- src/challenges/py/30DaysPy-26/README.md
- src/challenges/py/30DaysPy-26/playground.json
- src/challenges/py/30DaysPy-26/requirements.txt
- src/challenges/py/30DaysPy-26/src/main.py
- src/challenges/py/30DaysPy-26/src/main_test.py
- src/challenges/py/30DaysPy-26/src/tests.py
> new challenge taskOrganizer, challenge 30 dias de py

- src/challenges/py/30DaysPy-26/.gitignore
- src/challenges/py/30DaysPy-26/README.md
- src/challenges/py/30DaysPy-26/playground.json
- src/challenges/py/30DaysPy-26/requirements.txt
- src/challenges/py/30DaysPy-26/src/main.py
- src/challenges/py/30DaysPy-26/src/main_test.py
- src/challenges/py/30DaysPy-26/src/tests.py
> solution to taskOrganizer, challenge 30 dias de py

- src/challenges/py/30DaysPy-16/.gitignore
- src/challenges/py/30DaysPy-16/README.md
- src/challenges/py/30DaysPy-16/playground.json
- src/challenges/py/30DaysPy-16/requirements.txt
- src/challenges/py/30DaysPy-16/src/main.py
- src/challenges/py/30DaysPy-16/src/main_test.py
- src/challenges/py/30DaysPy-16/src/tests.py
> solution to taskOrganizerWithClosure, challenge 30 dias de py

- src/challenges/py/30DaysPy-16/.gitignore
- src/challenges/py/30DaysPy-16/README.md
- src/challenges/py/30DaysPy-16/playground.json
- src/challenges/py/30DaysPy-16/requirements.txt
- src/challenges/py/30DaysPy-16/src/main.py
- src/challenges/py/30DaysPy-16/src/main_test.py
- src/challenges/py/30DaysPy-16/src/tests.py
> new challenge taskOrganizerWithClosure, challenge 30 dias de py

- src/challenges/py/30DaysPy-27/.gitignore
- src/challenges/py/30DaysPy-27/README.md
- src/challenges/py/30DaysPy-27/playground.json
- src/challenges/py/30DaysPy-27/requirements.txt
- src/challenges/py/30DaysPy-27/src/Node.py
- src/challenges/py/30DaysPy-27/src/main.py
- src/challenges/py/30DaysPy-27/src/main_test.py
- src/challenges/py/30DaysPy-27/src/tests.py
> solution to patientList, challenge 30 dias de py

- src/challenges/py/30DaysPy-28/.gitignore
- src/challenges/py/30DaysPy-28/README.md
- src/challenges/py/30DaysPy-28/playground.json
- src/challenges/py/30DaysPy-28/requirements.txt
- src/challenges/py/30DaysPy-28/src/main.py
- src/challenges/py/30DaysPy-28/src/main_test.py
- src/challenges/py/30DaysPy-28/src/node.py
- src/challenges/py/30DaysPy-28/src/tests.py
> solution to playlist, challenge 30 dias de py

- src/challenges/py/30DaysPy-27/.gitignore
- src/challenges/py/30DaysPy-27/README.md
- src/challenges/py/30DaysPy-27/playground.json
- src/challenges/py/30DaysPy-27/requirements.txt
- src/challenges/py/30DaysPy-27/src/Node.py
- src/challenges/py/30DaysPy-27/src/main.py
- src/challenges/py/30DaysPy-27/src/main_test.py
- src/challenges/py/30DaysPy-27/src/tests.py
> new challenge patientList, challenge 30 dias de py

- src/challenges/py/30DaysPy-28/.gitignore
- src/challenges/py/30DaysPy-28/README.md
- src/challenges/py/30DaysPy-28/playground.json
- src/challenges/py/30DaysPy-28/requirements.txt
- src/challenges/py/30DaysPy-28/src/main.py
- src/challenges/py/30DaysPy-28/src/main_test.py
- src/challenges/py/30DaysPy-28/src/node.py
- src/challenges/py/30DaysPy-28/src/tests.py
> new challenge playlist, challenge 30 dias de py

- src/challenges/py/30DaysPy-29/.gitignore
- src/challenges/py/30DaysPy-29/README.md
- src/challenges/py/30DaysPy-29/playground.json
- src/challenges/py/30DaysPy-29/requirements.txt
- src/challenges/py/30DaysPy-29/src/mail.py
- src/challenges/py/30DaysPy-29/src/main.py
- src/challenges/py/30DaysPy-29/src/main_test.py
- src/challenges/py/30DaysPy-29/src/tests.py
> solution to queue, challenge 30 dias de py

- src/challenges/py/casting-en/.gitignore
- src/challenges/py/casting-en/README.md
- src/challenges/py/casting-en/playground.json
- src/challenges/py/casting-en/requirements.txt
- src/challenges/py/casting-en/src/main.py
- src/challenges/py/casting-en/src/main_test.py
- src/challenges/py/casting-en/src/tests.py
> :sparkles: [ADD] EN/casting
